version: '2.4'
services:
  backend:
    build: backend
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier
  mongo:
    image: mongo:latest
    restart: on-failure
    volumes:
      - db-data:/data/db
    networks:
      - back-tier
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  db-data:

networks:
  front-tier:
  back-tier:
